const { test, expect } = require('@playwright/test');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
const fs = require('node:fs');
const home = pathToFileURL(path.resolve(__dirname, '../../index.html')).href;

test('embedded dashboard, filters, comparison, mobile and CSV export', async ({ page }) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(home);
  await expect(page.locator('#dashboard')).toBeVisible();
  await expect(page.locator('#source-summary')).toContainText('300 รายการ');
  await expect(page.locator('#kpis .kpi').first()).toContainText('300');
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true });
  await page.locator('#dept').selectOption('PHA01');
  await expect(page.locator('#kpis .kpi').nth(1)).toContainText('59%');
  await page.getByRole('button', { name: 'รายการยา', exact: true }).click();
  await page.locator('#search').fill('11AZCT4');
  await expect(page.locator('#detail-table tbody tr')).toHaveCount(1);
  await expect(page.locator('#detail-table')).toContainText('-84');
  const downloadPromise = page.waitForEvent('download');
  await page.locator('#export').click();
  const download = await downloadPromise;
  const downloaded = fs.readFileSync(await download.path(), 'utf8');
  expect(downloaded).toContain('11AZCT4');
  expect(downloaded.trim().split('\r\n')).toHaveLength(2);
  await page.getByRole('button', { name: 'เทียบ PHA01 / PHA04', exact: true }).click();
  await expect(page.locator('#dept')).toBeDisabled();
  await expect(page.locator('#compare-table tbody tr')).toHaveCount(100);
  await page.locator('#both-diff').check();
  const both = await page.locator('#compare-table tbody tr').count();
  expect(both).toBeGreaterThan(0); expect(both).toBeLessThan(100);
  await page.locator('#reset').click();
  await page.getByRole('button', { name: 'ภาพรวมผลนับ', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true });
  expect(errors).toEqual([]);
});

test('local import, pending count, escaped HTML, atomic import failure and empty states', async ({ page }) => {
  await page.goto(home);
  await page.locator('#imports summary').click();
  await page.locator('#clear').click();
  await expect(page.locator('#empty')).toBeVisible();
  const header='CODE,DRUG_NAME,จำนวน/pack,C ย่อย),SUBSTOCK (หน่วยย่อย),นับได้ (pack),นับ เศษ,นับได้รวม (หน่วยย่อย),ผลต่าง นับ,type';
  const text=header+'\n11TEST,<img src=x onerror=alert(1)>,10,100,100,9,8,98,-2,Vital+Original\n11WAIT,Pending,10,100,100,,,,,Original';
  await page.locator('#count-files').setInputFiles({ name:'count_PHA01.csv', mimeType:'text/csv', buffer:Buffer.from(text) });
  await expect(page.locator('#kpis .kpi').first()).toContainText('ยังไม่นับ 1');
  await page.locator('#tolerance').selectOption('2');
  await expect(page.locator('#kpis .kpi').nth(1)).toContainText('100%');
  await page.getByRole('button', {name:'รายการยา',exact:true}).click();
  await expect(page.locator('#detail-table img')).toHaveCount(0);
  await expect(page.locator('#detail-table')).toContainText('<img src=x onerror=alert(1)>');
  await page.locator('#status').selectOption('pending');
  await expect(page.locator('#detail-table tbody tr')).toHaveCount(1);
  await page.locator('#count-files').setInputFiles({name:'count_PHA02.csv',mimeType:'text/csv',buffer:Buffer.from('wrong,header\na,b')});
  await expect(page.locator('#message')).toContainText('ไม่พบคอลัมน์');
  await expect(page.locator('#source-summary')).toContainText('1 แผนก · 2 รายการ');
  await page.locator('#status').selectOption('');
  await page.locator('#search').fill('nothing-matches');
  await expect(page.locator('#detail-table')).toContainText('ไม่พบรายการ');
});
